# Generated by Django 5.1.3 on 2025-04-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Club",
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("manage_geography", "Can manage geographic data")]
            },
        ),
        migrations.RemoveField(
            model_name="continent",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="continent",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="continent",
            name="updated_at",
        ),
        migrations.AlterUniqueTogether(
            name="country",
            unique_together={("code",), ("name", "continent")},
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="country",
            name="phone_code",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.RemoveField(
            model_name="country",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="country",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="country",
            name="updated_at",
        ),
    ]
