# Generated by Django 5.1.3 on 2025-04-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "geography",
            "0002_delete_club_alter_country_options_alter_user_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="continent",
            name="world_body",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
