# Generated by Django 5.1.3 on 2025-04-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0003_continent_world_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="continent",
            name="sport_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
