# Generated by Django 5.1.3 on 2025-04-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0004_continent_sport_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="continent",
            name="cont_federation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="continent",
            name="fedabrev",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
