# Generated by Django 5.1.3 on 2025-04-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0005_continent_cont_federation_continent_fedabrev"),
    ]

    operations = [
        migrations.AlterField(
            model_name="continent",
            name="code",
            field=models.CharField(max_length=2, unique=True, verbose_name="ISO Code"),
        ),
        migrations.AlterField(
            model_name="continent",
            name="cont_federation",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Federation"
            ),
        ),
        migrations.AlterField(
            model_name="continent",
            name="fedabrev",
            field=models.CharField(
                max_length=10, null=True, unique=True, verbose_name="Fed Abrev"
            ),
        ),
        migrations.AlterField(
            model_name="continent",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Continent"
            ),
        ),
        migrations.AlterField(
            model_name="continent",
            name="sport_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Sport Code"
            ),
        ),
        migrations.AlterField(
            model_name="continent",
            name="world_body",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="World Body"
            ),
        ),
    ]
