# Generated by Django 5.1.3 on 2025-04-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "geography",
            "0006_alter_continent_code_alter_continent_cont_federation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="continent",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Toggle to show/hide this continent in lists."
            ),
        ),
    ]
