# Generated by Django 5.1.3 on 2025-04-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0007_continent_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="continent",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Toggle to show/hide this continent in lists."
            ),
        ),
    ]
