# Generated by Django 5.1.3 on 2025-04-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0008_alter_continent_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="continent",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="continents/logos/"
            ),
        ),
    ]
