# Generated by Django 5.1.3 on 2025-04-26 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0009_add_logo_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="country",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="country",
            name="flag",
            field=models.ImageField(
                blank=True, null=True, upload_to="countries/flags/"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="continent",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="geography.continent",
            ),
        ),
        migrations.RemoveField(
            model_name="country",
            name="phone_code",
        ),
    ]
