# Generated by Django 5.1.3 on 2025-04-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "geography",
            "0010_alter_country_options_alter_country_unique_together_and_more",
        ),
    ]

    operations = []
