# Generated by Django 5.1.3 on 2025-04-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0011_jwt_setup"),
    ]

    operations = []
