# Generated by Django 5.1.3 on 2025-04-28 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0012_auto_20250428_2115"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "countries"},
        ),
        migrations.AlterField(
            model_name="continent",
            name="cont_federation",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Continental Body"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="country",
            unique_together={("code",), ("name", "continent")},
        ),
        migrations.CreateModel(
            name="RegionalBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
                (
                    "continent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="geography.continent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="country",
            name="regional_body",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geography.regionalbody",
            ),
        ),
    ]
