# Generated by Django 5.2 on 2025-04-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0013_alter_country_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalbody",
            name="continent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regional_bodies",
                to="geography.continent",
            ),
        ),
    ]
